#!/usr/bin/env python3
"""Assemble the two deployable artifacts from source modules.

  backend  : apps-script/*.gs  -> build/Code.gs      (paste/inject into Apps Script)
  frontend : index.html + frontend/view-*.js -> public/index.html  (GitHub Pages)

Load order matters: every module's ACTIONS_* const must exist before Router.gs merges them.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GS_ORDER = [
    'Config.gs', 'Seed.gs', 'Setup.gs', 'Auth.gs',
    # foundations must load before the pipeline modules that call them
    'SheetBridge.gs', 'Brain.gs',
    'Tasks.gs', 'Schedules.gs', 'Reports.gs', 'Messaging.gs',
    'Agenda.gs', 'Meetings.gs', 'RulesAck.gs',
    'Hunting.gs', 'Listing.gs', 'CpcResearch.gs', 'PotentialCpc.gs',
    'Advertising.gs', 'Orders.gs', 'Recheck.gs', 'CustomerService.gs', 'Embeds.gs',
    'Dashboard.gs', 'Alerts.gs', 'Performance.gs', 'Signals.gs', 'StaffAdmin.gs', 'Attendance.gs',
    'Integrity.gs', 'AuditAgent.gs', 'Engine.gs', 'NightBackup.gs',
    'R8.gs',
    'Router.gs', 'Registry.gs',
]
MARKER = '/* === PHASE 3 VIEW MODULES SPLICED HERE === */'


def strip_strings_and_comments(src):
    """Blank out string literals and comments so a delimiter count reflects code, not prose.
    A brace inside "s.charAt(0) === '{'" is data, and counting it reports a phantom error."""
    out, i, n = [], 0, len(src)
    # A '/' starts a regex (not division) when the previous meaningful char opens an expression.
    regex_start = set('(,=:[!&|?{};+-*%~^') | {'\n'}
    while i < n:
        c = src[i]
        if c == '/' and i + 1 < n and src[i + 1] not in '/*':
            prev = ''
            for j in range(len(out) - 1, -1, -1):
                if not out[j].isspace():
                    prev = out[j]
                    break
            tail = ''.join(out[-8:]).rstrip()
            if prev in regex_start or prev == '' or tail.endswith('return') or tail.endswith('typeof'):
                i += 1
                in_class = False
                while i < n:
                    if src[i] == '\\':
                        i += 2
                        continue
                    if src[i] == '[':
                        in_class = True
                    elif src[i] == ']':
                        in_class = False
                    elif src[i] == '/' and not in_class:
                        break
                    elif src[i] == '\n':
                        break
                    i += 1
                i += 1
                while i < n and src[i].isalpha():   # flags
                    i += 1
                out.append('R')
                continue
            out.append(c)
            i += 1
        elif c in '"\'`':
            quote, i = c, i + 1
            while i < n and src[i] != quote:
                i += 2 if src[i] == '\\' else 1
            i += 1
            out.append('""')
        elif c == '/' and i + 1 < n and src[i + 1] == '/':
            while i < n and src[i] != '\n':
                i += 1
        elif c == '/' and i + 1 < n and src[i + 1] == '*':
            i += 2
            while i + 1 < n and not (src[i] == '*' and src[i + 1] == '/'):
                i += 1
            i += 2
        else:
            out.append(c)
            i += 1
    return ''.join(out)


def build_backend():
    parts = ['/** M98M PORTAL BACKEND — generated by scripts/build.py. Edit the modules, not this file. */\n']
    missing = []
    for name in GS_ORDER:
        path = os.path.join(ROOT, 'apps-script', name)
        if not os.path.exists(path):
            missing.append(name)
            continue
        with open(path) as fh:
            parts.append('\n// ==================== %s ====================\n%s' % (name, fh.read()))
    out = '\n'.join(parts)
    os.makedirs(os.path.join(ROOT, 'build'), exist_ok=True)
    dest = os.path.join(ROOT, 'build', 'Code.gs')
    with open(dest, 'w') as fh:
        fh.write(out)

    code = strip_strings_and_comments(out)
    for open_ch, close_ch, label in (('{', '}', 'braces'), ('(', ')', 'parens'), ('[', ']', 'brackets')):
        if code.count(open_ch) != code.count(close_ch):
            print('  WARN unbalanced %s: %d vs %d' % (label, code.count(open_ch), code.count(close_ch)))
    actions = sorted(set(re.findall(r'\bACTIONS_[A-Z]+\b', out)))
    print('backend -> build/Code.gs  %d bytes, %d functions, action groups: %s'
          % (len(out), out.count('function '), ', '.join(actions) or 'none'))
    if missing:
        print('  missing modules (skipped): %s' % ', '.join(missing))
    return missing


def build_frontend():
    # Source shell lives in src/ — the ROOT index.html is the BUILT page, because GitHub
    # Pages serves this repo's root as the live portal (main branch, path "/"). A push of the
    # source shell to root once served an empty frame to the whole team; never again.
    with open(os.path.join(ROOT, 'src', 'shell.html')) as fh:
        shell = fh.read()
    if MARKER not in shell:
        sys.exit('ERROR: splice marker missing from index.html')
    fdir = os.path.join(ROOT, 'frontend')
    files = sorted(f for f in os.listdir(fdir) if f.endswith('.js')) if os.path.isdir(fdir) else []
    blocks = []
    for name in files:
        with open(os.path.join(fdir, name)) as fh:
            blocks.append('/* ---------- %s ---------- */\n%s' % (name, fh.read().strip()))
    page = shell.replace(MARKER, '\n\n'.join(blocks) if blocks else MARKER)

    # Stamp the bundle and publish the same stamp to version.txt: the shell's versionWatch()
    # compares the two and self-reloads stale tabs, so a deploy actually reaches every screen.
    import time
    stamp = time.strftime('%Y%m%d-%H%M', time.gmtime())
    page = page.replace('__BUILD_STAMP__', stamp)

    with open(os.path.join(ROOT, 'index.html'), 'w') as fh:
        fh.write(page)
    with open(os.path.join(ROOT, 'version.txt'), 'w') as fh:
        fh.write(stamp + '\n')
    # engine source staged at root too: the dash-pane deploy fetches it from the live site
    with open(os.path.join(ROOT, 'engine', 'worker.js')) as fh:
        eng = fh.read()
    with open(os.path.join(ROOT, 'engine-worker.txt'), 'w') as fh:
        fh.write(eng)
    print('build stamp: %s (root index.html, version.txt, engine-worker.txt written)' % stamp)
    views = sorted(set(re.findall(r'VIEWS\.([A-Za-z0-9_]+)\s*=', page)))
    print('frontend -> public/index.html  %d bytes, modules: %d, views: %s'
          % (len(page), len(files), ', '.join(views)))
    return views


if __name__ == '__main__':
    print('Building M98M Portal...')
    build_backend()
    build_frontend()
