#!/usr/bin/env python3
"""Assemble the two deployable artifacts from source modules.

  backend  : apps-script/*.gs  -> build/Code.gs      (paste/inject into Apps Script)
  frontend : index.html + frontend/view-*.js -> public/index.html  (GitHub Pages)

Load order matters: every module's ACTIONS_* const must exist before Router.gs merges them.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GS_ORDER = [
    'Config.gs', 'Seed.gs', 'Setup.gs', 'Auth.gs',
    # foundations must load before the pipeline modules that call them
    'SheetBridge.gs', 'Brain.gs',
    'Tasks.gs', 'Schedules.gs', 'Reports.gs', 'Messaging.gs',
    'Agenda.gs', 'Meetings.gs', 'RulesAck.gs',
    'Hunting.gs', 'Listing.gs', 'CpcResearch.gs', 'PotentialCpc.gs',
    'Router.gs', 'Registry.gs',
]
MARKER = '/* === PHASE 3 VIEW MODULES SPLICED HERE === */'


def build_backend():
    parts = ['/** M98M PORTAL BACKEND — generated by scripts/build.py. Edit the modules, not this file. */\n']
    missing = []
    for name in GS_ORDER:
        path = os.path.join(ROOT, 'apps-script', name)
        if not os.path.exists(path):
            missing.append(name)
            continue
        with open(path) as fh:
            parts.append('\n// ==================== %s ====================\n%s' % (name, fh.read()))
    out = '\n'.join(parts)
    os.makedirs(os.path.join(ROOT, 'build'), exist_ok=True)
    dest = os.path.join(ROOT, 'build', 'Code.gs')
    with open(dest, 'w') as fh:
        fh.write(out)

    for open_ch, close_ch, label in (('{', '}', 'braces'), ('(', ')', 'parens'), ('[', ']', 'brackets')):
        if out.count(open_ch) != out.count(close_ch):
            print('  WARN unbalanced %s: %d vs %d' % (label, out.count(open_ch), out.count(close_ch)))
    actions = sorted(set(re.findall(r'\bACTIONS_[A-Z]+\b', out)))
    print('backend -> build/Code.gs  %d bytes, %d functions, action groups: %s'
          % (len(out), out.count('function '), ', '.join(actions) or 'none'))
    if missing:
        print('  missing modules (skipped): %s' % ', '.join(missing))
    return missing


def build_frontend():
    with open(os.path.join(ROOT, 'index.html')) as fh:
        shell = fh.read()
    if MARKER not in shell:
        sys.exit('ERROR: splice marker missing from index.html')
    fdir = os.path.join(ROOT, 'frontend')
    files = sorted(f for f in os.listdir(fdir) if f.endswith('.js')) if os.path.isdir(fdir) else []
    blocks = []
    for name in files:
        with open(os.path.join(fdir, name)) as fh:
            blocks.append('/* ---------- %s ---------- */\n%s' % (name, fh.read().strip()))
    page = shell.replace(MARKER, '\n\n'.join(blocks) if blocks else MARKER)

    os.makedirs(os.path.join(ROOT, 'public', 'assets'), exist_ok=True)
    with open(os.path.join(ROOT, 'public', 'index.html'), 'w') as fh:
        fh.write(page)
    views = sorted(set(re.findall(r'VIEWS\.([A-Za-z0-9_]+)\s*=', page)))
    print('frontend -> public/index.html  %d bytes, modules: %d, views: %s'
          % (len(page), len(files), ', '.join(views)))
    return views


if __name__ == '__main__':
    print('Building M98M Portal...')
    build_backend()
    build_frontend()
